### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

### 查询课程信息2
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 101,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "fdsd",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "dsadasdasfasaasd",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级java网络编程高级"
}

### 根据课程id查询课程信息
GET {{content_host}}/content/course/40
Content-Type: application/json

### 课程查询
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 修改老师
PUT {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 79,
  "teacherName": "李四郎",
  "position": "培训二级讲师",
  "introduction": "张天师传人，负责推广",
  "photograph": null,
  "position": "培训二级讲师",
  "teacherName": "李四郎"
}

